import axios from 'axios';
import db from './db';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
const GITHUB_API_BASE = 'https://api.github.com';

interface Finding {
  type: string;
  severity: string;
  file_path?: string;
  line_number?: number;
  message: string;
  suggestion?: string;
}

interface ReviewData {
  review_id: number;
  repo: string;
  pr_number: number;
  quality_score: number;
  findings: Finding[];
}

function formatComment(reviewData: ReviewData): string {
  const { quality_score, findings } = reviewData;

  // Get top 3 suggestions (prioritize by severity: critical > high > medium > low)
  const severityOrder = { critical: 4, high: 3, medium: 2, low: 1 };
  const topFindings = findings
    .sort((a, b) => (severityOrder[b.severity as keyof typeof severityOrder] || 0) - 
                    (severityOrder[a.severity as keyof typeof severityOrder] || 0))
    .slice(0, 3);

  let comment = `## 🤖 AI Code Review\n\n`;
  comment += `**Quality Score:** ${quality_score}/100\n\n`;

  if (topFindings.length > 0) {
    comment += `### Top Suggestions:\n\n`;
    
    topFindings.forEach((finding, index) => {
      comment += `${index + 1}. **${finding.type.replace('_', ' ').toUpperCase()}** `;
      
      if (finding.file_path) {
        comment += `(${finding.file_path}`;
        if (finding.line_number) {
          comment += `:${finding.line_number}`;
        }
        comment += `) `;
      }
      
      comment += `- ${finding.message}`;
      
      if (finding.suggestion) {
        comment += `\n   💡 *Suggestion:* ${finding.suggestion}`;
      }
      
      comment += `\n\n`;
    });
  } else {
    comment += `✅ No major issues found!\n\n`;
  }

  comment += `---\n*Generated by AI Code Reviewer*`;

  return comment;
}

export async function postGitHubComment(reviewData: ReviewData): Promise<string | null> {
  const { repo, pr_number } = reviewData;

  if (!GITHUB_TOKEN) {
    console.warn('GITHUB_TOKEN not set, skipping GitHub comment');
    return null;
  }

  try {
    const comment = formatComment(reviewData);
    const url = `${GITHUB_API_BASE}/repos/${repo}/issues/${pr_number}/comments`;

    const response = await axios.post(
      url,
      { body: comment },
      {
        headers: {
          'Authorization': `Bearer ${GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github.v3+json',
          'User-Agent': 'AI-Code-Reviewer-Orchestrator'
        }
      }
    );

    const commentId = response.data.id?.toString();
    console.log(`Posted GitHub comment ${commentId} for ${repo}#${pr_number}`);

    // Store comment ID in database
    await db('reviews')
      .where({ id: reviewData.review_id })
      .update({ github_comment_id: commentId });

    return commentId;
  } catch (error: any) {
    console.error(`Error posting GitHub comment for ${repo}#${pr_number}:`, error.message);
    if (error.response) {
      console.error('GitHub API response:', error.response.status, error.response.data);
    }
    return null;
  }
}

