import axios from 'axios';
import db from './db';
import config from './config';

const GITHUB_TOKEN = config.githubToken;
const GITHUB_API_BASE = 'https://api.github.com';

interface Finding {
  type: string;
  severity: string;
  file_path?: string;
  line_number?: number;
  message: string;
  suggestion?: string;
}

const severityOrder: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };

/**
 * Posts findings as inline code review comments on a GitHub Pull Request
 * using the Pull Request Reviews API.
 *
 * Each finding with a file_path and line_number is posted directly on that
 * specific line of the diff, giving developers contextual in-place feedback.
 *
 * @returns The GitHub review ID as a string, or null on failure.
 */
export async function postGitHubReview(
  repo: string,
  prNumber: number,
  commitSha: string,
  findings: Finding[]
): Promise<string | null> {
  if (!GITHUB_TOKEN) {
    console.warn('[github-service] GITHUB_TOKEN not set, skipping GitHub review');
    return null;
  }

  try {
    // Sort findings by severity descending for the overall summary
    const sortedFindings = [...findings].sort(
      (a, b) =>
        (severityOrder[b.severity] || 0) - (severityOrder[a.severity] || 0)
    );

    // Build inline comment objects for findings that have a file path + line number
    const inlineComments = sortedFindings
      .filter((f) => f.file_path && f.line_number)
      .map((f) => {
        const typeLabel = f.type.replace(/_/g, ' ').toUpperCase();
        const severityEmoji = { critical: '🔴', high: '🟠', medium: '🟡', low: '🟢' }[f.severity] || '⚪';

        let body = `### ${severityEmoji} AI Finding [${typeLabel} - ${f.severity.toUpperCase()}]\n\n${f.message}`;

        if (f.suggestion) {
          // GitHub renders ```suggestion blocks as suggested code changes the developer can apply with one click
          body += `\n\n\`\`\`suggestion\n${f.suggestion}\n\`\`\``;
        }

        return {
          path: f.file_path!,
          line: f.line_number!,
          side: 'RIGHT', // RIGHT = lines added in the new version of the file
          body,
        };
      });

    // Build the overall PR review body summary
    const qualityNote =
      sortedFindings.length > 0
        ? `Found **${sortedFindings.length} issue(s)**: ${sortedFindings
            .slice(0, 3)
            .map((f) => `_${f.type.replace(/_/g, ' ')}_`)
            .join(', ')} and more.`
        : '✅ No major issues found.';

    const reviewBody = `## 🤖 AI Code Review Summary\n\n${qualityNote}\n\nInline suggestions have been added to the affected lines. Review them in the **Files Changed** tab.\n\n---\n*Generated by the Context-Aware AI Code Reviewer*`;

    const response = await axios.post(
      `${GITHUB_API_BASE}/repos/${repo}/pulls/${prNumber}/reviews`,
      {
        commit_id: commitSha,
        event: 'COMMENT', // COMMENT = posts without approving or requesting changes
        body: reviewBody,
        comments: inlineComments,
      },
      {
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          Accept: 'application/vnd.github.v3+json',
          'User-Agent': 'AI-Code-Reviewer-Orchestrator',
        },
      }
    );

    const reviewId = response.data.id?.toString();
    console.log(`[github-service] Posted inline review ${reviewId} on ${repo}#${prNumber} with ${inlineComments.length} inline comment(s)`);
    return reviewId;
  } catch (error: any) {
    console.error(`[github-service] Error posting review on ${repo}#${prNumber}:`, error.message);
    if (error.response) {
      console.error(`[github-service] GitHub API responded with ${error.response.status}:`, error.response.data);
    }
    return null;
  }
}
